### ISSUE TITLE
Changing appearance for dummies

### ISSUE THREAD

**Issue by Arkoxs** [eouia/MMM-CalendarExt#16]
Hi there,

I'm using your calendar module as a family planner, on the background images are displayed by using the RandomBackground module. I've assigned an own text color (style) to every family member (4) and tried to remove all other background colors. That did not work for me.

Is it possible to display the calendar with just text and no background?

This is in my custom.css
.CALEXT .styleB .eventContainer{
  background-color:#000000;
  color:#00FFFF;
}

.CALEXT .styleB.fulldayevent .eventContainer{
  background-color:#000000;
  color:#00FFFF;
}

.CALEXT .styleA .eventContainer{
  background-color:#000000;
  color:#FF5D00;
}

.CALEXT .styleA.fulldayevent .eventContainer{
  background-color:#000000;
  color:#FF5D00;
}

.CALEXT .styleD .eventContainer{
  background-color:#000000;
  color:#B6FF00;
}

.CALEXT .styleD.fulldayevent .eventContainer{
  background-color:#000000;
  color:#B6FF00;
}

.CALEXT .styleY .eventContainer{
  background-color:#000000;
  color:#FF70FF;
}

.CALEXT .styleY.fulldayevent .eventContainer{
  background-color:#000000;
  color:#FF70FF;
}

.CALEXT .styleH .eventContainer{
  background-color:#000000;
  color:#FFFFFF;
}

.CALEXT .styleH.fulldayevent .eventContainer{
  background-color:#000000;
  color:#FFFFFF;
}
![schermafbeelding 2017-11-08 om 12 08 46](https://user-images.githubusercontent.com/3475376/32546960-fe3cbd06-c480-11e7-8330-b98beb78a161.png)

**Comment by eouia** [comment]
Have you tried Background transparency?
#000000 -> rgba(0,0,0,0) // the 4th parameter is for transparency as I remembered.
I think it could work

**Comment by Arkoxs** [comment]
Hi Eouia,
Changing hex to rgba(0,0,0,0) did not work, the result is a grey background.
![schermafbeelding 2017-11-08 om 14 30 58](https://user-images.githubusercontent.com/3475376/32551816-10229e3a-c492-11e7-8859-838b6ed4d093.png)

**Comment by eouia** [comment]
Ok. I'll check it. wait a few hours.

**Comment by eouia** [comment]
Ok. in your customized, CSS,
remove all `background-color` from custom styles.
```css
.CALEXT .styleY .eventContainer{
/* background-color:#000000; */  //remove these;
color:#FF70FF;
}
```
and append these code.

```css
div.CALEXT li.event {
  background-color:rgba(0,0,0,0);
}

div.CALEXT li.event div.eventContainer {
  background-color:rgba(0,0,0,0);
}
```
But In this case, you can have a difficult to distinguish each events.
You can consider `rgba(0,0,0,0.2)` instead. or draw border.
