### ISSUE TITLE
customize color for current week saturday and sunday

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt#76]
Is it possible to change the background color of just to top cell for Saturdayand Sunday?

![image](https://user-images.githubusercontent.com/41309095/68565474-7789f200-0408-11ea-9b35-4125fc5ecf0a.png)

**Comment by eouia** [comment]
You can use this CSS selector for it;
```css
.CALEXT .weekHeader .day_6
```
`day_1` is Monday, `day_7` is Sunday. 

So, you can use like this;
```css
.CALEXT .weekHeader .day_6 {
  background-color: yellow;
  color: black;
}
```
<img width="467" alt="12" src="https://user-images.githubusercontent.com/1720610/68569842-733cf380-045f-11ea-9146-cfff1536ad9d.png">
